micronaut:
  application:
    name: report_service
  server:
    port: 8081
    context-path: /report/api/v0
    dual-protocol: true
  ssl:
    enabled: true
    port: 8083
    key-store:
      password: 123456a@
      path: classpath:ssl/server.jks
      type: JKS
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      redoc:
        paths: classpath:META-INF/swagger/views/redoc
        mapping: /redoc/**
      rapidoc:
        paths: classpath:META-INF/swagger/views/rapidoc
        mapping: /rapidoc/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

datasources:
  default:
    url: jdbc:mysql://localhost:3306/tek4tv_report
    driverClassName: com.mysql.cj.jdbc.Driver
    username: tek4tv_report
#    password: '123456a@'
    password: 'tek4tv'
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

ovp:
  url: https://playback.tek4tv.vn/v1